nt 2
uncaught TaskErrors: 1 errors: IllegalArgumentError: 2
  pod-no-tlvy.chpl:48: thrown here
  pod-no-tlvy.chpl:48: uncaught here
starting task
finished task
asdf(1), returning
asdf(10), returning
asdf(1000), returning
1101000
asdf(2), throwing
