feature request/error message: recursive standalone iterators

When writing a recursive standalone iterator, we get a somewhat
confusing error message pointing to an internal module.  This future
can be perceived as a feature request to add support for recursive
standalone parallel iterators, if possible.  Or, if not, as a request
to improve the error message if there's a good reason that we can't
support recursive standalone iterators.
