coercingIntToSyncIntOnConstructor.chpl:6: In function 'main':
coercingIntToSyncIntOnConstructor.chpl:7: error: unresolved call 'Foo.init(1)'
coercingIntToSyncIntOnConstructor.chpl:1: note: candidates are: Foo.init(x$: _syncvar(int(64)))
