─── error in function-and-record.chpl:2 [Redefinition] ───
  'foo' has multiple definitions.
  It was first defined here:
      |
    2 |   proc foo(x: int) { }
      |        ⎺⎺⎺
      |
  Redefined here:
      |
    3 |   record foo { }
      |   ⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺⎺
      |

