dest_existed.chpl:3: error: File exists in copyTree(a, existing_dir)
